### ISSUE TITLE
Paintings move

### ISSUE THREAD

**Issue by OysterStew** [Luke100000/ImmersivePaintings#10]
Upon saving and then loading a world in again in MC 1.18.2 paintings are moving 1/2 block down and/or to the right or left.

**Comment by OysterStew** [comment]
Just realized I'm using a older version of the mod. Will repost if there is an issue with latest version

**Comment by Luke100000** [comment]
Theoretically this has been dealt with in the latest version, please let me know if it still happens!

**Comment by OysterStew** [comment]
Version 2.0 fixes it.
