### ISSUE TITLE
Paintings can't be inside eachother

### ISSUE THREAD

**Issue by Lucky-56** [Luke100000/ImmersivePaintings#14]
You can't place a painting on the floor with a painting already on the wall
![image](https://user-images.githubusercontent.com/55949451/200083274-430c843c-69b2-4407-9871-1109458619b5.png)

I think this comes from the normal painting code that two paintings can't be inside eachother,
but as your paintings are able to be placed on floors and ceilings this is redundant for that reason

possible fix:
- paintings that are on the same axis will break eachother as usual
- paintings that are not on the same axis won't break eachother

**Forge:** 43.1.47
**Mod Version:** 0.3.1

**Comment by Luke100000** [comment]
Your fix sounds reasonably, thanks! You can produce overlapping paintings that way but z fighting will be minimal so I think its fine

**Comment by Lucky-56** [comment]
you can already place paintings inside non-full blocks so z-fighting is basically already there ;)
