### ISSUE TITLE
[Feature Request] Server Moderation

### ISSUE THREAD

**Issue by Alkiasan** [Luke100000/ImmersivePaintings#15]
Hi, I really love your mod, and i've been using it on my server for a while!

I was wondering if it would ever be possible for Opped players to delete paintings uploaded by other players, and also for paintings to be made Private so normal players can't see them (Our server has events that we'd love to use these paintings for, but the players can spoil themselves before even participating!)

Again, this is a great mod, and I understand if you don't wish to include these features

**Comment by Luke100000** [comment]
Sure, both suggestions are good and on my todo :)
