### ISSUE TITLE
Freezes at "joining world"

### ISSUE THREAD

**Issue by Defnotanton** [Luke100000/ImmersivePaintings#16]
**Describe the bug**
My friend's birthday is soon and i wanna use this mod for him but it just keeps crashing when i try to join
It also does not work with my friends too

**Latest.log**
https://mclo.gs/WeOBusZ - client
https://mclo.gs/zzDMlEe - server

**Expected behavior**
Joining the server with no problems

**Comment by Luke100000** [comment]
A quick google suggests that this error usually occurs in relation with spigot servers, as spigot rejects mods trying to do networking. Fabricproxy also points into that direction. Is this correct? Do you need fabricproxy?

If you are the server admin, try this: https://www.reddit.com/r/admincraft/comments/gttzpz/how_to_allow_modded_clients_to_join_a_spigot/

Theoretically this problem should occur with every mod which requires custom networking, and as far as I read there isn't really anything I can do.

https://github.com/shedaniel/RoughlyEnoughItems/issues/99 states that he fixed that issue, and it looks like reducing the message ids size helped. Which is weird, but if the first approach fails I can try that.

**Comment by Defnotanton** [comment]
I use minehut btw does that effect anything?
