### ISSUE TITLE
1.19.2 - Please Add a tool for removing paintings

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Luke100000/ImmersivePaintings#32]
It shocked me to realize no tool except voiding the block or creative mod allows you to remove paintings. I even tried the infamous debug stick ... can you please fix this as soon as possible?

**Comment by Luke100000** [comment]
No need for a tool, the intended way is to slap it. If that doesn't work you may have a mod conflict, please send me the latest log.

**Comment by P3rf3ctXZer0** [comment]
I will when I can. If what you say is true there is an issue.
