### ISSUE TITLE
1.19.2 - Frame Size and Orientation Preview.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Luke100000/ImmersivePaintings#33]
A much larger issue than removing a painting https://github.com/Luke100000/ImmersivePaintings/issues/32 is placing. The placement system should most certainly have a preview system. The fact that it does not at least have a white outline similar to Building gadgets is baffling.

**Comment by Luke100000** [comment]
A preview doesn't work since you do not know the size on placement. The orientation is always the face you click on.

**Comment by P3rf3ctXZer0** [comment]
You cannot do something like little tiles that creates a white outline?
