### ISSUE TITLE
Adding paintings via datapack doesn't work

### ISSUE THREAD

**Issue by devvoid** [Luke100000/ImmersivePaintings#54]
**Describe the bug**
Adding paintings via datapack doesn't work, logging this message:

`[23:34:24] [Render thread/ERROR]: Failed to list path /data/minecraft/datapacks/bundle/assets`

The example pack with its one example painting seems to work fine, but adding anything else does not work.

**Latest.log**
[latest.log](https://github.com/Luke100000/ImmersivePaintings/files/12572250/latest.log)

**To Reproduce**
Add this datapack to a world using the 1.20 version of the mod.
[pack_that_isnt_working.zip](https://github.com/Luke100000/ImmersivePaintings/files/12572243/pack_that_isnt_working.zip)

**Comment by Luke100000** [comment]
Works fine for me, how did you install it? What kind of server? Can you try without zipping as it looks like a file read error.

**Comment by devvoid** [comment]
I tried zipping it and it seems to work now? Weird that it seemingly can't read unzipped, but at least it's going now
