### ISSUE TITLE
Paintings are editable in adventure mode

### ISSUE THREAD

**Issue by Octelly** [Luke100000/ImmersivePaintings#55]
**Describe the bug**
Paintings are editable even in adventure mode. I believe, they should only be editable in modes, where you can build (e.g. survival and creative).

**Latest.log**
N/A

**To Reproduce**
1. place an item from this mod
2. go into adventure mode
3. painting/graffiti is still editable

**Expected behavior**
The painting should not be editable.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Luke100000** [comment]
fixed
