### ISSUE TITLE
Stuck at uploading 0 seconds left

### ISSUE THREAD

**Issue by SkyTheDerg** [Luke100000/ImmersivePaintings#60]
**Describe the bug**
Hiya, not to sure what could be causing this. all the paintings are blank, and when uploading custom image it gets stuck at 0 seconds remaining in multiplayer 

**Latest.log**
attached at the bottom of report

**To Reproduce**
add any painting or uploading any link

**Screenshots**

![javaw_YQwqBvQ3sz](https://github.com/Luke100000/ImmersivePaintings/assets/146779121/d7b197dd-4ba2-4c98-8842-57851d94fc22)
![javaw_UVJcTb8IMo](https://github.com/Luke100000/ImmersivePaintings/assets/146779121/6758361f-57b4-4a60-ae27-b38a407f37e0)

**Additional context**
[log.txt](https://github.com/Luke100000/ImmersivePaintings/files/12786314/log.txt)

**Comment by Luke100000** [comment]
I need the full log, and make sure that both server and client are up to date. I assume that the server is not.

**Comment by SkyTheDerg** [comment]
both sides are up to date with the same version "0.6.3+1.18.2" the full log has been running for about 12 hours but I can try and generate a short one for you

**Comment by Neko-Desu1** [comment]
I have also been having the same issue, adding any image or url will get stuck at 0 sec. 
[Bug.txt](https://github.com/Luke100000/ImmersivePaintings/files/12797347/Bug.txt)

**Comment by Luke100000** [comment]
> I have also been having the same issue, adding any image or url will get stuck at 0 sec. [Bug.txt](https://github.com/Luke100000/ImmersivePaintings/files/12797347/Bug.txt)

You, however, have a very outdated version :)

**Comment by Luke100000** [comment]
> both sides are up to date with the same version "0.6.3+1.18.2" the full log has been running for about 12 hours but I can try and generate a short one for you

You too btw, specifically 0.6.4 fixed networking related crashes which is what you have here. Worth a try.

**Comment by Luke100000** [comment]
Alright so please try 0.6.4, a version which should have fixed that issue a while ago but as I just see, uploading failed for forge back then. I just pushed 0.6.6, try that one.

**Comment by SkyTheDerg** [comment]
Updating fixed it!! Thank you so much for the support <3
