### ISSUE TITLE
Can't place paintings while in creative/survival mode

### ISSUE THREAD

**Issue by talltimog** [Luke100000/ImmersivePaintings#61]
Hello! Just made a server 1.20.1, and installed Create and Immersive Paintings through curseforge app. Tried using the paintings in both creative mode and survival, but everytime I right click nothing happens , even though my number of paintings would decrease. Unsure what could be causing it to not place on a block. 
I am very new to minecraft modding!

**Comment by Luke100000** [comment]
Does it work in singleplayer? Can you drop an item on the server? If not, then its not installed server side.

If yes, log please, in the minecraft dir at logs/latest.log

**Comment by proxyline77** [comment]
same thing for me. it works in single but it's not working on my server

**Comment by Luke100000** [comment]
> same thing for me. it works in single but it's not working on my server

and, did you try the drop trick?

**Comment by proxyline77** [comment]
yes it drops

**Comment by Luke100000** [comment]
> yes it drops

then append the log, server and client

**Comment by talltimog** [comment]
> Does it work in singleplayer? Can you drop an item on the server? If not, then its not installed server side.
> 
> If yes, log please, in the minecraft dir at logs/latest.log

It does work in singleplayer! And no it doesnt drop item in the multiplayer server! So I have to install it onto the server and not just through curseforge?

**Comment by Luke100000** [comment]
> > Does it work in singleplayer? Can you drop an item on the server? If not, then its not installed server side.
> > If yes, log please, in the minecraft dir at logs/latest.log
> 
> It does work in singleplayer! And no it doesnt drop item in the multiplayer server! So I have to install it onto the server and not just through curseforge?

Unrelated to how you install it, you need to make sure its installed on both client and server.

**Comment by talltimog** [comment]
> > > Does it work in singleplayer? Can you drop an item on the server? If not, then its not installed server side.
> > > If yes, log please, in the minecraft dir at logs/latest.log
> > 
> > 
> > It does work in singleplayer! And no it doesnt drop item in the multiplayer server! So I have to install it onto the server and not just through curseforge?
> 
> Unrelated to how you install it, you need to make sure its installed on both client and server.

Thank you for the help! It started working now!

**Comment by proxyline77** [comment]
i realized that i have the versions of the mod are different on the server and client so i changed that and now it works
