### ISSUE TITLE
not working on a server

### ISSUE THREAD

**Issue by Tomskiiii** [Luke100000/ImmersivePaintings#67]
when ever i right click on the graffiti tile on the server i play on it crashes me from the server and all it says is this 

java.lang.IndexOutOfBoundsException: readerIndex(5) + length(4) exceeds writerIndex(5): UnpooledSlicedByteBuf(ridx: 5, widx: 5, cap: 5/5, unwrapped: PooledUnsafeDirectByteBuf(ridx: 0, widx: 5, cap: 5))

i dont know how to fix it please help

**Comment by Luke100000** [comment]
make sure server and client have the same version

**Comment by Tomskiiii** [comment]
they are it was working yesterday but for some reason some of the players can use it but others have the same issue as i do

**Comment by Luke100000** [comment]
then please send me client and server latest logs

**Comment by Tomskiiii** [comment]
i dont have access to the servers latest logs but i can send my ends
one moment

**Comment by Tomskiiii** [comment]
actual it fixed itself i have no idea what happened but its fine now
