### ISSUE TITLE
Same painting, different sizes

### ISSUE THREAD

**Issue by DoktorCraft** [Luke100000/ImmersivePaintings#70]
**Describe the bug**
So i have Graffiti 1 that is 9x2 and i have Graffiti 2 that i want to be 15x5. Now when i make the Graffiti 2, Graffiti 1 also grows to 15x5. Both Graffitis have the same picture. Version: 0.6.7+1.19.2

**Latest.log**
None.

**To Reproduce**
1. Make Graffiti 1 15x5 and put picture A in.
2. Make Graffiti 2 9x2 and put picture A in.
3. Check Graffiti 1.

**Expected behavior**
Graffiti 1 should behold its former size.

**Screenshots**
![2024-03-01_14 58 34](https://github.com/Luke100000/ImmersivePaintings/assets/123328292/f9024576-041b-4a67-a82d-85ea20468584)
Graffiti 1 after Graffiti 2 was made.

**Additional context**
Hope i get an answer soon.

**Comment by Luke100000** [comment]
Then change the name. If you use the same name it will overwrite the painting.

**Comment by DoktorCraft** [comment]
The name of the file?

**Comment by Luke100000** [comment]
The name in the painting creation. By default it uses the file/url name, but can be changed freely.

**Comment by DoktorCraft** [comment]
Ohh thanks! Love your mod
